# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

include:
  # JDK 11
  - name: "Java 11"
    stage: test
    jdk: openjdk11
script: travis_retry ./gradlew check install



# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -denisshustroff@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always